# GitHub Action for generating a contribution graph with a snake eating your contributions.
# Thanks https://github.com/Platane/snk

name: Generate Snake


on:
  watch:
    types: started
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./assets/github-snake.svg
            ./assets/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: 'Generate Contribution Snake'
          default_author: github_actions
